development:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: red_packet

test:
  adapter: test

production:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: red_packet
